# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Project1

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release

steps:
#Use .Net 5
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true

#Prepare SonarCloud Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ryantowner'
    scannerMode: 'MSBuild'
    projectKey: 'ryantowner_project1'
    projectName: 'project1'

#Build
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: 'Project1'

#Run SonarCloud Analysis
- task: SonarCloudAnalyze@1

#Run Tests
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    testRunTitle: 'Test Run'
    workingDirectory: 'Project1'

#Publish
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(build.artifactstagingdirectory)'
  
- task: PublishBuildArtifacts@1

