# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Project1

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: 'Project1'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    #arguments: '$(build.artifactstagingdirectory)'
  
- task: PublishBuildArtifacts@1